// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNxUV0VqxUnlTzdCUNToq7JMl5m9bIh8w',
    appId: '1:762882527116:web:ad91127f464e9eaad3d0a9',
    messagingSenderId: '762882527116',
    projectId: 'inclass13-fc770',
    authDomain: 'inclass13-fc770.firebaseapp.com',
    storageBucket: 'inclass13-fc770.firebasestorage.app',
    measurementId: 'G-BSNDYQN3TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNeqpJDZPY6g0o5uV_qBvKCqIdFDMEI5U',
    appId: '1:762882527116:android:e1c8d16ea38eddc2d3d0a9',
    messagingSenderId: '762882527116',
    projectId: 'inclass13-fc770',
    storageBucket: 'inclass13-fc770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQXTBcmmIEPuicElJPMwfW-qzqDXe4aHg',
    appId: '1:762882527116:ios:8381a6119f793178d3d0a9',
    messagingSenderId: '762882527116',
    projectId: 'inclass13-fc770',
    storageBucket: 'inclass13-fc770.firebasestorage.app',
    iosBundleId: 'com.example.madInclass13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQXTBcmmIEPuicElJPMwfW-qzqDXe4aHg',
    appId: '1:762882527116:ios:8381a6119f793178d3d0a9',
    messagingSenderId: '762882527116',
    projectId: 'inclass13-fc770',
    storageBucket: 'inclass13-fc770.firebasestorage.app',
    iosBundleId: 'com.example.madInclass13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNxUV0VqxUnlTzdCUNToq7JMl5m9bIh8w',
    appId: '1:762882527116:web:549a06500583d2fdd3d0a9',
    messagingSenderId: '762882527116',
    projectId: 'inclass13-fc770',
    authDomain: 'inclass13-fc770.firebaseapp.com',
    storageBucket: 'inclass13-fc770.firebasestorage.app',
    measurementId: 'G-4C2ZDYG9J7',
  );
}
